# Generated by Django 5.2.14 on 2026-05-06 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=40, unique=True)),
                ("client_nom", models.CharField(max_length=255)),
                ("date_emission", models.DateField()),
                ("date_echeance", models.DateField()),
                ("montant_ttc", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("emise", "Émise"),
                            ("partiellement_reglee", "Partiellement réglée"),
                            ("reglee", "Réglée"),
                            ("annulee", "Annulée"),
                        ],
                        default="emise",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "ordering": ["date_echeance", "reference"],
            },
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_paiement", models.DateField()),
                ("montant", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("virement", "Virement"),
                            ("carte", "Carte"),
                            ("mobile_money", "Mobile Money"),
                        ],
                        default="virement",
                        max_length=32,
                    ),
                ),
                ("reference_operation", models.CharField(blank=True, max_length=80)),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="finance.facture",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_paiement", "-id"],
            },
        ),
    ]
